### ISSUE TITLE
Why dividing 3.0 for feature stride in RoIAlign?

### ISSUE THREAD

**Issue by nnop** [TuSimple/mx-maskrcnn#49]
In the following codes:
https://github.com/TuSimple/mx-maskrcnn/blob/e8a05daf058375d8b9f07ddd581d035da1b4d472/rcnn/CXX_OP/roi_align.cu#L72-L73, you use `3.0` computing strides. Why use `3.0`? Shouldn't it be `pooled_height` or `pooled_width`?

@huangzehao  @Zehaos

**Comment by Zehaos** [comment]
Hi, @nnop 
We choose 4 localizations inside the bin, not four corners of the bin. In the author's talk in iccv2017, [slide](http://kaiminghe.com/iccv17tutorial/maskrcnn_iccv2017_tutorial_kaiminghe.pdf) page 24, they claim that other implementation should work. But I think choose 4 corners is not a good choice, because there are overlap between adjacent bins.

**Comment by nnop** [comment]
Thanks for responding and referring me Kaiming's slides.

Wouldn't it loss information by sampling only 2 points if a cell contain many, like in a big RoI?

**Comment by Zehaos** [comment]
Oh, this is a interesting topic. I think we know little about ROI Pooling. I think sample more point could help, but I haven't prove it.
