### ISSUE TITLE
question about test time consume

### ISSUE THREAD

**Issue by zouxinh** [TuSimple/mx-maskrcnn#78]
Thanks for your work first, there are some questions:
 
(1) I want to know how much time you test a image ( eg: Cityscape image with size 1024,2048), and what is your hardware. (ps: I run the 'demo_single_image', and I get 1.25s when test a image with size 1080,1920)

(2) What is the most time consume part of maskrcnn (fpn or mask brance) ?

**Comment by Zehaos** [comment]
Hi, @zouxinh 
A1. This repo can't not reproduce the speed as mentioned in the paper, we still working on this. It is normal of your measurement.
A2. FPN is time consuming because we should process several feature levels rather than one. I think the mask branch is not very time consuming, because the feature map provided by the ROIAlign is only 14*14.

**Comment by zouxinh** [comment]
thanks for your reply. 
I manager to drop the FPN by set config.RPN_FEAT_STRIDE =[32] and config.RCNN_FEAT_STRIDE = [32] and train a model. The time I test is almost 1.0s which reduce 20% time consume, so I think the FPN structure is not the most time consume part.

**Comment by Zehaos** [comment]
Here is a paper investigate this problem. [Light-Head R-CNN: In Defense of Two-Stage Object Detector](https://arxiv.org/abs/1711.07264). Hope it helps.

**Comment by zouxinh** [comment]
ok, than you again.

**Comment by 315386775** [comment]
@zouxinh how about the memory consume when you test one image.
